[package]
name = "murmurhash"
version = "0.1.0"
authors = ["alsotang <alsotang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

bytes = "0.5.6"
